- name: Clone Repo
  git:
    repo: "{{ repository }}"
    dest: "/home/{{ ansible_user }}/{{ app }}"
    force: yes
    accept_hostkey: yes
    key_file: "/home/{{ ansible_user }}/.ssh/cgus-bot-key"
  register: git_clone_app_finished
  tags:
    - setup
    - update

- name: Install NPM packages
  command:
    cmd: npm i --production --unsafe-perm=true --production=true
    chdir: "/home/{{ ansible_user }}/{{ app }}"
  tags:
    - setup
    - update

- name: Add .env file
  copy:
    src: .env
    dest: "/home/{{ ansible_user }}/{{ app }}/.env"
  tags:
    - setup

- name: Stop CGUs
  command: forever stop "{{ app }}"
  ignore_errors: yes
  tags:
    - restart
    - stop
    - update

- include_tasks: database.yml
  vars:
    name: CGUS-Snapshots
    repository: "{{ snapshots_repository }}"
    directory: "{{ snapshots_directory }}"

- include_tasks: database.yml
  vars:
    name: CGUS-Versions
    repository: "{{ versions_repository }}"
    directory: "{{ versions_directory }}"

- name: Start CGUs
  command:
    cmd: forever start -m 10 -a --uid "{{ app }}" -c "npm run start:scheduler:prod" ./
    chdir: "/home/{{ ansible_user }}/{{ app }}"
  environment:
    NODE_ENV: production
  tags:
    - restart
    - start
    - update
