---
- name: Install common required packages
  apt:
    pkg:
      - curl
      - build-essential
      - git
      - zip
    update_cache: yes
    state: latest

- name: Add global Git Config
  copy:
    src: .gitconfig
    dest: '/home/{{ ansible_user }}/.gitconfig'

- name: Add the NodeSource repository to the system
  shell: curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -

- name: Install NodeJS and Npm
  apt:
    name: nodejs
    update_cache: yes
    state: latest

- name: Update Npm to latest version
  command: npm install -g npm

- name: Install pm2
  command: npm install -g pm2 --production=true

- name: Add GitHub SSH key
  copy:
    src: ota-bot-key.private_key
    dest: '/home/{{ ansible_user }}/.ssh/ota-bot-key'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: 0600

- name: Configure SSH to use Ansible key for github.com
  template:
    src: ssh_config.j2
    dest: '/home/{{ ansible_user }}/.ssh/config'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: 0644

- name: Install Chromium
  apt:
    pkg:
      - chromium
    update_cache: yes
    state: latest

  # See https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#recommended-enable-user-namespace-cloning
- name: Enable user namespace cloning to allow running Chromium in a sandbox
  command: sysctl -w kernel.unprivileged_userns_clone=1

- include_tasks: mongo.yml
